inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/*"

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
