version: "3"

services:
  db:
    container_name: postgres
    image: postgres:13.3-alpine
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  customer_service:
    container_name: customer_service
    build: ./customer_service
    volumes:
      - ./customer_service:/app/customer_service
    depends_on:
      - db
    ports:
      - "4000:4000"
  frontend:
    container_name: frontend
    image: "node:14.17-alpine"
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: "npm run dev"
    depends_on:
      - customer_service
    ports:
      - "3000:3000"
